-- MySQL Script generated by MySQL Workbench
-- Fri Sep  8 14:23:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dankdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dankdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dankdb` DEFAULT CHARACTER SET utf8 ;
USE `dankdb` ;

-- -----------------------------------------------------
-- Table `dankdb`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dankdb`.`games` ;

CREATE TABLE IF NOT EXISTS `dankdb`.`games` (
  `id` INT(11) NOT NULL,
  `gameName` VARCHAR(64) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dankdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dankdb`.`users` ;

CREATE TABLE IF NOT EXISTS `dankdb`.`users` (
  `id` INT(11) NOT NULL,
  `username` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dankdb`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dankdb`.`team` ;

CREATE TABLE IF NOT EXISTS `dankdb`.`team` (
  `id` INT(11) NOT NULL,
  `teamName` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Users_id` INT(11) NOT NULL,
  `team_leader` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Users_id`),
  UNIQUE INDEX `team_leader_UNIQUE` (`team_leader` ASC),
  INDEX `fk_Team_Users_idx` (`Users_id` ASC),
  CONSTRAINT `fk_team_leader`
    FOREIGN KEY (`team_leader`)
    REFERENCES `dankdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_Users`
    FOREIGN KEY (`Users_id`)
    REFERENCES `dankdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dankdb`.`team_has_games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dankdb`.`team_has_games` ;

CREATE TABLE IF NOT EXISTS `dankdb`.`team_has_games` (
  `Team_id` INT(11) NOT NULL,
  `Team_Users_id` INT(11) NOT NULL,
  `Games_id` INT(11) NOT NULL,
  PRIMARY KEY (`Team_id`, `Team_Users_id`, `Games_id`),
  INDEX `fk_Team_has_Games_Games1_idx` (`Games_id` ASC),
  INDEX `fk_Team_has_Games_Team1_idx` (`Team_id` ASC, `Team_Users_id` ASC),
  CONSTRAINT `fk_Team_has_Games_Games1`
    FOREIGN KEY (`Games_id`)
    REFERENCES `dankdb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_has_Games_Team1`
    FOREIGN KEY (`Team_id` , `Team_Users_id`)
    REFERENCES `dankdb`.`team` (`id` , `Users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dankdb`.`tournaments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dankdb`.`tournaments` ;

CREATE TABLE IF NOT EXISTS `dankdb`.`tournaments` (
  `id` INT(11) NOT NULL,
  `t_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Games_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tournaments_Games1_idx` (`Games_id` ASC),
  CONSTRAINT `fk_Tournaments_Games1`
    FOREIGN KEY (`Games_id`)
    REFERENCES `dankdb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dankdb`.`team_has_tournaments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dankdb`.`team_has_tournaments` ;

CREATE TABLE IF NOT EXISTS `dankdb`.`team_has_tournaments` (
  `Team_id` INT(11) NOT NULL,
  `Team_Users_id` INT(11) NOT NULL,
  `Tournaments_id` INT(11) NOT NULL,
  PRIMARY KEY (`Team_id`, `Team_Users_id`, `Tournaments_id`),
  INDEX `fk_Team_has_Tournaments_Tournaments1_idx` (`Tournaments_id` ASC),
  INDEX `fk_Team_has_Tournaments_Team1_idx` (`Team_id` ASC, `Team_Users_id` ASC),
  CONSTRAINT `fk_Team_has_Tournaments_Team1`
    FOREIGN KEY (`Team_id` , `Team_Users_id`)
    REFERENCES `dankdb`.`team` (`id` , `Users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_has_Tournaments_Tournaments1`
    FOREIGN KEY (`Tournaments_id`)
    REFERENCES `dankdb`.`tournaments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dankdb`.`team_game_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dankdb`.`team_game_stats` ;

CREATE TABLE IF NOT EXISTS `dankdb`.`team_game_stats` (
  `teamId` INT NOT NULL,
  `gameId` INT NOT NULL,
  `Wins` INT NULL,
  `Losses` INT NULL,
  PRIMARY KEY (`teamId`, `gameId`),
  INDEX `id_idx` (`gameId` ASC),
  CONSTRAINT `Team_id`
    FOREIGN KEY (`teamId`)
    REFERENCES `dankdb`.`team_has_games` (`Team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`gameId`)
    REFERENCES `dankdb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
